collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.4950827853754163
  brandStrength: 1
  lightness: 0.6229283083230257
  brandColors:
    - '#FFFFFF'
    - '#007B91'
    - '#4B5059'
    - '#6FC6EF'
    - '#918F90'
  rhythmicContrast: 0.3089240854606032
typography_spectrum: 0.01612659520469606
layout_spectrum: 0
name: spruce^ki
