collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.7939068
  brandStrength: 1
  lightness: 0.8817204
  brandColors:
    - '#FFFFFF'
    - '#007B91'
    - '#4B5059'
    - '#6FC6EF'
    - '#918F90'
  rhythmicContrast: 0
typography_spectrum: 0.4336918
layout_spectrum: 0.4103943
name: spruce^ki
navigation:
  - name: Cron
    url: 'https://github.com/seam/cron'
    type: external
  - name: Cache Dup
    url: 'http://screamingcoder.com/life/2013/07/20/cache-dup/'
    type: external
  - name: Open Source
    id: f405e688-e4f8-429a-bb44-7e8e03ee7e2f
    type: content
